spring:
  application:
    name: sp001
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/sp001_db?useSSL=false&serverTimezone=UTC&characterEncoding=utf8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}

mybatis:
  mapper-locations: classpath:mybatisXML/*.xml
  type-aliases-package: com.sp001.pojo
  configuration:
    map-underscore-to-camel-case: true